### PR TITLE
Added context parsing and adjusted parser logic.

### PR DESCRIPTION
**Pull request by eldarc**
This enables the use of context keywords. Example: `{{ pgettext('title', 'A message to be translated') }}` and `{{ pgettext('article', 'A message to be translated') }}` are registered as two messages.

### CODE REVIEW

**Comment by smhg** [comment]
Thank you for your work. Do you plan to send a new PR?
I'll have a look at it right away.

You can definitely use ES6 features as long as you set it up for previous node versions too.

**Comment by eldarc** [comment]
Yes, I'm going to make a new PR after I test it a bit more carefully.

This one was a bit rushed. :)

**Comment by smhg** [comment]
Great! Thanks!
The Swig parser was kind of neglected because the project Readme says it is no longer maintained.
You know anything about the future of Swig?

**Comment by eldarc** [comment]
I'm actually writing this because it's compatible with Nunjucks. So, I'm going to adapt this later as a Nunjucks parser.

**Pull request closed without merging**
